# Generated by Django 5.0.6 on 2024-06-28 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='agree_to_terms',
        ),
    ]
