# Generated by Django 5.0.6 on 2024-06-28 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_agree_to_terms'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
